// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Lyapunov
Rcpp::List Lyapunov(Rcpp::List timeSeries, Rcpp::List outputSpikes);
RcppExport SEXP Rdnn_Lyapunov(SEXP timeSeriesSEXP, SEXP outputSpikesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type timeSeries(timeSeriesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type outputSpikes(outputSpikesSEXP);
    __result = Rcpp::wrap(Lyapunov(timeSeries, outputSpikes));
    return __result;
END_RCPP
}
// PpClassKernelRun
Rcpp::NumericMatrix PpClassKernelRun(Rcpp::List preProcConfig, Rcpp::List kernelConfig, Rcpp::List timeSeries, size_t jobs, double dt);
RcppExport SEXP Rdnn_PpClassKernelRun(SEXP preProcConfigSEXP, SEXP kernelConfigSEXP, SEXP timeSeriesSEXP, SEXP jobsSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type preProcConfig(preProcConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type kernelConfig(kernelConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type timeSeries(timeSeriesSEXP);
    Rcpp::traits::input_parameter< size_t >::type jobs(jobsSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    __result = Rcpp::wrap(PpClassKernelRun(preProcConfig, kernelConfig, timeSeries, jobs, dt));
    return __result;
END_RCPP
}
// ClassKernelRun
Rcpp::NumericMatrix ClassKernelRun(Rcpp::List kernelConfig, Rcpp::List timeSeries, size_t jobs);
RcppExport SEXP Rdnn_ClassKernelRun(SEXP kernelConfigSEXP, SEXP timeSeriesSEXP, SEXP jobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type kernelConfig(kernelConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type timeSeries(timeSeriesSEXP);
    Rcpp::traits::input_parameter< size_t >::type jobs(jobsSEXP);
    __result = Rcpp::wrap(ClassKernelRun(kernelConfig, timeSeries, jobs));
    return __result;
END_RCPP
}
// PpKernelRun
Rcpp::List PpKernelRun(Rcpp::List preProcConfig, Rcpp::List kernelConfig, Rcpp::List timeSeries, size_t jobs, double dt, bool timeCorrelation);
RcppExport SEXP Rdnn_PpKernelRun(SEXP preProcConfigSEXP, SEXP kernelConfigSEXP, SEXP timeSeriesSEXP, SEXP jobsSEXP, SEXP dtSEXP, SEXP timeCorrelationSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type preProcConfig(preProcConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type kernelConfig(kernelConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type timeSeries(timeSeriesSEXP);
    Rcpp::traits::input_parameter< size_t >::type jobs(jobsSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< bool >::type timeCorrelation(timeCorrelationSEXP);
    __result = Rcpp::wrap(PpKernelRun(preProcConfig, kernelConfig, timeSeries, jobs, dt, timeCorrelation));
    return __result;
END_RCPP
}
// KernelRun
Rcpp::List KernelRun(Rcpp::List kernelConfig, Rcpp::List timeSeries, size_t jobs, bool timeCorrelation);
RcppExport SEXP Rdnn_KernelRun(SEXP kernelConfigSEXP, SEXP timeSeriesSEXP, SEXP jobsSEXP, SEXP timeCorrelationSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type kernelConfig(kernelConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type timeSeries(timeSeriesSEXP);
    Rcpp::traits::input_parameter< size_t >::type jobs(jobsSEXP);
    Rcpp::traits::input_parameter< bool >::type timeCorrelation(timeCorrelationSEXP);
    __result = Rcpp::wrap(KernelRun(kernelConfig, timeSeries, jobs, timeCorrelation));
    return __result;
END_RCPP
}
// PreprocessRun
Rcpp::List PreprocessRun(Rcpp::List preProcConfig, Rcpp::List timeSeries, size_t jobs);
RcppExport SEXP Rdnn_PreprocessRun(SEXP preProcConfigSEXP, SEXP timeSeriesSEXP, SEXP jobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type preProcConfig(preProcConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type timeSeries(timeSeriesSEXP);
    Rcpp::traits::input_parameter< size_t >::type jobs(jobsSEXP);
    __result = Rcpp::wrap(PreprocessRun(preProcConfig, timeSeries, jobs));
    return __result;
END_RCPP
}
// setVerboseLevel
void setVerboseLevel(int level);
RcppExport SEXP Rdnn_setVerboseLevel(SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    setVerboseLevel(level);
    return R_NilValue;
END_RCPP
}
// chopTimeSeries
Rcpp::List chopTimeSeries(Rcpp::List l);
RcppExport SEXP Rdnn_chopTimeSeries(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type l(lSEXP);
    __result = Rcpp::wrap(chopTimeSeries(l));
    return __result;
END_RCPP
}
// chopSpikesList
Rcpp::List chopSpikesList(Rcpp::List l);
RcppExport SEXP Rdnn_chopSpikesList(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type l(lSEXP);
    __result = Rcpp::wrap(chopSpikesList(l));
    return __result;
END_RCPP
}
// binarizeSpikes
Rcpp::List binarizeSpikes(Rcpp::List l, double dt);
RcppExport SEXP Rdnn_binarizeSpikes(SEXP lSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    __result = Rcpp::wrap(binarizeSpikes(l, dt));
    return __result;
END_RCPP
}
