# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setVerboseLevel <- function(level) {
    invisible(.Call('Rdnn_setVerboseLevel', PACKAGE = 'Rdnn', level))
}

dnnCleanHeap <- function() {
    invisible(.Call('Rdnn_dnnCleanHeap', PACKAGE = 'Rdnn'))
}

