// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// setVerboseLevel
void setVerboseLevel(int level);
RcppExport SEXP Rdnn_setVerboseLevel(SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    setVerboseLevel(level);
    return R_NilValue;
END_RCPP
}
// dnnCleanHeap
void dnnCleanHeap();
RcppExport SEXP Rdnn_dnnCleanHeap() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    dnnCleanHeap();
    return R_NilValue;
END_RCPP
}
