# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lyapunov <- function(timeSeries, outputSpikes) {
    .Call('Rdnn_Lyapunov', PACKAGE = 'Rdnn', timeSeries, outputSpikes)
}

pp.class.kernel.run <- function(preProcConfig, kernelConfig, timeSeries, jobs, dt = 1.0) {
    .Call('Rdnn_PpClassKernelRun', PACKAGE = 'Rdnn', preProcConfig, kernelConfig, timeSeries, jobs, dt)
}

class.kernel.run <- function(kernelConfig, timeSeries, jobs) {
    .Call('Rdnn_ClassKernelRun', PACKAGE = 'Rdnn', kernelConfig, timeSeries, jobs)
}

pp.kernel.run <- function(preProcConfig, kernelConfig, timeSeries, jobs, dt = 1.0, timeCorrelation = FALSE) {
    .Call('Rdnn_PpKernelRun', PACKAGE = 'Rdnn', preProcConfig, kernelConfig, timeSeries, jobs, dt, timeCorrelation)
}

kernel.run <- function(kernelConfig, timeSeries, jobs, timeCorrelation) {
    .Call('Rdnn_KernelRun', PACKAGE = 'Rdnn', kernelConfig, timeSeries, jobs, timeCorrelation)
}

preprocess.run <- function(preProcConfig, timeSeries, jobs) {
    .Call('Rdnn_PreprocessRun', PACKAGE = 'Rdnn', preProcConfig, timeSeries, jobs)
}

set.verbose.level <- function(level) {
    invisible(.Call('Rdnn_setVerboseLevel', PACKAGE = 'Rdnn', level))
}

chop.time.series <- function(l) {
    .Call('Rdnn_chopTimeSeries', PACKAGE = 'Rdnn', l)
}

chop.spikes.list <- function(l) {
    .Call('Rdnn_chopSpikesList', PACKAGE = 'Rdnn', l)
}

binarize.spikes <- function(l, dt = 1.0) {
    .Call('Rdnn_binarizeSpikes', PACKAGE = 'Rdnn', l, dt)
}

get.rate.vectors <- function(l, winLength = 10.0) {
    .Call('Rdnn_getRateVectors', PACKAGE = 'Rdnn', l, winLength)
}

